site_name: OpenAPI-core
site_description: OpenAPI for Python
site_url: https://openapi-core.readthedocs.io/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: lime
    accent: amber
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: lime
    accent: amber
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
repo_name: python-openapi/openapi-core
repo_url: https://github.com/python-openapi/openapi-core
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            unwrap_annotated: true
            docstring_section_style: spacy
            separate_signature: true
            signature_crossrefs: true
            show_category_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
nav:
  - OpenAPI-core: index.md
  - unmarshalling.md
  - validation.md
  - Integrations:
    - integrations/index.md
    - integrations/aiohttp.md
    - integrations/bottle.md
    - integrations/django.md
    - integrations/falcon.md
    - integrations/fastapi.md
    - integrations/flask.md
    - integrations/pyramid.md
    - integrations/requests.md
    - integrations/starlette.md
    - integrations/tornado.md
    - integrations/werkzeug.md
  - configuration.md
  - security.md
  - extensions.md
  - Reference:
    - reference/index.md
    - reference/openapi.md
    - reference/configurations.md
    - reference/datatypes.md
    - reference/protocols.md
    - reference/types.md
  - contributing.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-J6T05Z51NY
